baseURL: "https://peterkuehne.com/"
languageCode: "en-gb"
title: "Peter Kühne's Blog"
enableEmoji: true
disqusShortname: "peterkuehne"
theme: "mainroad"

menu:
  main:
    - identifier: posts
      name: Blog
      url: /posts/
      weight: 1
    - identifier: network
      name: Home Network
      url: /categories/home-network
      weight: 2
    - identifier: miniatures
      name: Miniatures
      url: /categories/miniatures
      weight: 3
    - identifier: genealogy
      name: Genealogy
      url: /categories/genealogy
      weight: 4
    - identifier: queue
      name: Painting Challenge
      url: /challenge/
      weight: 9
    - identifier: about
      name: About
      url: /about/
      weight: 10

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  defaultMarkdownHandler: goldmark

# Mainroad Theme
params:
  progress:
    - name: "Painting Challenge"
      file: challenge-2022
  twitter_cards: true
  readmore: true
  authorbox: false
  post_navigation: true
  post_meta:
    - "date"
    - "categories"
    - "series"
  mainSections:
    - "posts"
  dateformat: "2006-01-02"
  sidebar:
    home: "right"
    list: "right"
    single: "right"
    widgets:
      - "ddg-search"
      - "progress"
      - "recent"
      - "categories"
      - "taglist"
      - "social"
  widgets:
    recent_num: 3
    tags_counter: true
    social:
      facebook: "quantumpete"
      twitter: "peter_kuehne"
      instagram: "peter.kuehne"
      linkedin: "peter-kuehne"
      github: "pkuehne"
      email: "pkuehne.webmaster@mailnull.com"
