baseURL: "https://peterkuehne.com/"
languageCode: "en-gb"
title: "Peter Kühne's Blog"
enableEmoji: true
disqusShortname: "peterkuehne"
theme: "mainroad"

menu:
  main:
    - identifier: posts
      name: Blog
      url: /posts/
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 0

taxonomies:
  category: categories
  tag: tags
  series: series
  
markup:
  defaultMarkdownHandler: goldmark
      
# Mainroad Theme
params:
  twitter_cards: true
  readmore: true
  authorbox: false
  post_navigation: true
  post_meta:
    - "date"
    - "categories"
    # - "series"
  mainSections:
    - "posts"
    - "about"
  dateformat: "2006-01-02"
  sidebar:
    home: "right"
    list: "right"
    single: "right"
    widgets:
      - "recent"
      - "categories"
      - "taglist"
      - "social"
  widgets:
    recent_num: 3
    tags_counter: true
    social:
      facebook: "quantumpete"
      twitter: "peter_kuehne"
      instagram: "peter.kuehne"
      linkedin: "peter-kuehne"
      github: "pkuehne"
      email: "webmaster@peterkuehne.com"